import { User, Category, Tag, Article, Comment } from '../types';

export const initialCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'T20 & Leagues',
    slug: 'ipl-t20-leagues',
    description: 'High-octane action, franchise insights, auctions, and tactical breakdowns from IPL and world leagues.',
    display_order: 1,
    created_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-2',
    name: 'Test Cricket',
    slug: 'test-cricket',
    description: 'Test match reports, series previews and the World Test Championship.',
    display_order: 2,
    created_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-3',
    name: 'ICC Events',
    slug: 'icc-events',
    description: 'World Cup, Champions Trophy and other ICC tournament coverage.',
    display_order: 3,
    created_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-4',
    name: 'Analysis',
    slug: 'analysis',
    description: 'Tactical breakdowns, stats deep-dives and feature writing.',
    display_order: 4,
    created_at: new Date('2026-01-01').toISOString(),
  },
  {
    id: 'cat-5',
    name: "Women's Cricket",
    slug: 'womens-cricket',
    description: 'WPL sensations, ICC Women’s Championships, and the rapidly growing landscape of global women’s cricket.',
    display_order: 5,
    created_at: new Date('2026-01-01').toISOString(),
  },
];

export const initialTags: Tag[] = [
  { id: 'tag-1', name: 'IPL 2026', slug: 'ipl-2026', created_at: new Date().toISOString() },
  { id: 'tag-2', name: 'Jasprit Bumrah', slug: 'jasprit-bumrah', created_at: new Date().toISOString() },
  { id: 'tag-3', name: 'Virat Kohli', slug: 'virat-kohli', created_at: new Date().toISOString() },
  { id: 'tag-4', name: 'Pat Cummins', slug: 'pat-cummins', created_at: new Date().toISOString() },
  { id: 'tag-5', name: 'WTC Final', slug: 'wtc-final', created_at: new Date().toISOString() },
  { id: 'tag-6', name: 'Bazball', slug: 'bazball', created_at: new Date().toISOString() },
  { id: 'tag-7', name: 'Smriti Mandhana', slug: 'smriti-mandhana', created_at: new Date().toISOString() },
  { id: 'tag-8', name: 'Match Analysis', slug: 'match-analysis', created_at: new Date().toISOString() },
];

export const initialUsers: User[] = [
  {
    id: 'user-admin',
    email: 'admin@CricFax.com',
    full_name: 'Vikram Merchant',
    username: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    bio: 'Chief Editor & Platform Administrator at CricFax. Covering international cricket for over 18 years.',
    role: 'ADMIN',
    is_active: true,
    created_at: new Date('2025-01-01').toISOString(),
    updated_at: new Date('2025-01-01').toISOString(),
  },
  {
    id: 'user-author-1',
    email: 'harsha@CricFax.com',
    full_name: 'Ananya Deshmukh',
    username: 'ananya_cricket',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    bio: 'Lead Tactical Analyst and WPL correspondent. Passionate about swing mechanics, field placements, and data storytelling.',
    role: 'AUTHOR',
    is_active: true,
    created_at: new Date('2025-02-15').toISOString(),
    updated_at: new Date('2025-02-15').toISOString(),
  },
  {
    id: 'user-author-2',
    email: 'michael@CricFax.com',
    full_name: 'Alastair Vance',
    username: 'vance_cricket',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Senior Cricket Correspondent based in London. Covering Test cricket, England tours, and County Championships.',
    role: 'AUTHOR',
    is_active: true,
    created_at: new Date('2025-03-01').toISOString(),
    updated_at: new Date('2025-03-01').toISOString(),
  },
  {
    id: 'user-reader',
    email: 'reader@CricFax.com',
    full_name: 'Rohan Mehra',
    username: 'rohan_fan',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Cricket enthusiast, amateur leg-spinner, and passionate follower of Test cricket.',
    role: 'READER',
    is_active: true,
    created_at: new Date('2025-04-10').toISOString(),
    updated_at: new Date('2025-04-10').toISOString(),
  }
];

export const initialArticles: Article[] = [
  {
    id: 'art-1',
    title: 'The Art of the Reverse-Swing Yorker: How Bumrah Redefined Death Bowling in Test Cricket',
    slug: 'art-of-reverse-swing-yorker-bumrah-death-bowling',
    excerpt: 'An anatomical exploration of Jasprit Bumrah’s unique release point, seam presentation, and psychological mastery over the world’s finest batsmen.',
    content: `When Jasprit Bumrah marks his idiosyncratic eight-step run-up, opposition dressing rooms invariably turn silent. Over the past decade, cricket purists wondered whether an unorthodox action featuring hyper-extended hyperextension could endure the rigors of five-day Test matches.\n\nNot only has Bumrah survived; he has revitalized reverse-swing bowling into a lethal, deterministic science. Unlike traditional swing bowlers who depend on lush overhead conditions and fresh lacquer, Bumrah thrives when pitches are abrasive, dry, and unresponsive.\n\n### The Geometry of Deception\n\nTraditional seamers release the ball with an upright wrist cocked strictly behind the seam. Bumrah, however, operates with a hyperextended elbow and a snap of the forearm that propels the ball from almost 20 centimeters closer to the popping crease than average pacers. This subtle spatial displacement compresses a batsman's reaction window by approximately 45 milliseconds.\n\n> "You think you have judged the trajectory at 145 kph, but by the time your bat descends, the ball has dipped six inches and crashed into off-stump." — Former International Captain\n\n### Data Breakdown: Bumrah in the Final 10 Overs\n\n1. **Dot Ball Percentage**: 62.4% across SENA countries.\n2. **Average Speed of Wicket-Taking Deliveries**: 142.8 km/h.\n3. **Seam Deviation Angle**: 2.3 degrees off straight at the point of pitching.\n\nAs cricket moves inexorably toward batting dominance and shorter boundaries, Bumrah remains the supreme equalizer—an artist with red and white leather who reminds us why bowling is cricket’s truest thrill.`,
    featured_image_url: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80',
    author_id: 'user-author-1',
    category_id: 'cat-2',
    status: 'PUBLISHED',
    match_format: 'TEST',
    is_breaking: true,
    is_featured: true,
    read_time_minutes: 6,
    views_count: 14250,
    published_at: new Date('2026-09-24T10:00:00Z').toISOString(),
    created_at: new Date('2026-09-24T08:00:00Z').toISOString(),
    updated_at: new Date('2026-09-24T10:00:00Z').toISOString(),
  },
  {
    id: 'art-2',
    title: 'IPL Auction Dynamics: Why Powerplay Anchors Are Being Replaced by 200+ Strike-Rate Dashers',
    slug: 'ipl-auction-dynamics-powerplay-strike-rates-evolution',
    excerpt: 'The statistical revolution in franchise T20 cricket: How the impact player rule and analytical models transformed how teams construct top-order batting lineups.',
    content: `For nearly fifteen years, the prevailing dogma of Twenty20 cricket was deceptively simple: protect wickets in the powerplay, consolidate through overs 7 to 14, and unleash mayhem during the final death overs.\n\nIn 2026, that playbook has been decisively incinerated.\n\nModern data science teams across IPL franchises have concluded that a 35-ball 40 is frequently more detrimental to winning probabilities than a 12-ball 28. With batting depths routinely extending down to number nine and ten thanks to the Impact Sub rule, the marginal value of wicket conservation in the first six overs has plunged.\n\n### The Shift to Intent Above Average\n\n- **2018 Powerplay Average Run Rate**: 7.82 RPO\n- **2022 Powerplay Average Run Rate**: 8.45 RPO\n- **2026 Powerplay Average Run Rate**: 10.15 RPO\n\nFranchises are no longer scouting for elegant stroke-makers who require fifteen deliveries to get their eyes in. They seek fearless ball-strikers capable of sending the first delivery over long-on, regardless of who is running in.`,
    featured_image_url: 'https://images.unsplash.com/photo-1531415074868-036b1c5f53ec?auto=format&fit=crop&w=1200&q=80',
    author_id: 'user-admin',
    category_id: 'cat-1',
    status: 'PUBLISHED',
    match_format: 'IPL',
    is_breaking: false,
    is_featured: true,
    read_time_minutes: 5,
    views_count: 9830,
    published_at: new Date('2026-09-23T14:30:00Z').toISOString(),
    created_at: new Date('2026-09-23T12:00:00Z').toISOString(),
    updated_at: new Date('2026-09-23T14:30:00Z').toISOString(),
  },
  {
    id: 'art-3',
    title: 'WPL 2026 Grand Finale Preview: Battle of Spin Prowess and Explosive Middle Orders',
    slug: 'wpl-2026-grand-finale-preview-tactical-preview',
    excerpt: 'Everything you need to know ahead of the championship showdown: Key matchups, pitch conditions at Brabourne Stadium, and players to watch.',
    content: `The stage is set for an electrifying final in the Women’s Premier League. Both finalists have conquered contrasting tactical journeys to reach Mumbai’s historic Brabourne Stadium.\n\nThe contest promises to hinge on how Mumbai's spin trio handles the sheer boundary-hitting frequency of Delhi's middle order during the middle overs.\n\n### Matchup of the Night\n\nSmriti Mandhana’s imperious form through off-side cover drives faces an exacting examination against high-pace incoming inswing. Early wickets will dictate whether we witness a 190+ run feast or a battle of grit and stamina on a pitch that traditionally slows down under lights.`,
    featured_image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=1200&q=80',
    author_id: 'user-author-1',
    category_id: 'cat-5',
    status: 'PUBLISHED',
    match_format: 'T20I',
    is_breaking: true,
    is_featured: false,
    read_time_minutes: 4,
    views_count: 7640,
    published_at: new Date('2026-09-24T06:15:00Z').toISOString(),
    created_at: new Date('2026-09-24T05:00:00Z').toISOString(),
    updated_at: new Date('2026-09-24T06:15:00Z').toISOString(),
  },
  {
    id: 'art-4',
    title: 'World Test Championship 2027 Scenarios: Who Holds the Advantage Ahead of Lord’s Showdown?',
    slug: 'world-test-championship-2027-qualification-scenarios-lords',
    excerpt: 'With five high-stakes bilateral series remaining, we calculate percentage points, penalty overs, and qualification pathways for India, Australia, and South Africa.',
    content: `The mathematical race for the ICC World Test Championship mace enters its decisive phase. With points contested on a percentage basis rather than aggregate totals, every drawn match and slow over-rate penalty carries monumental ramifications.\n\nAustralia’s upcoming tour of the subcontinent poses the quintessential litmus test. If the Baggy Greens secure two victories, their place at Lord’s is virtually rubber-stamped. Meanwhile, India must navigate a grueling five-match overseas assignment where bonus points will prove crucial.\n\n### Current Standings & Projected Points Percentage\n\n1. **Australia**: 68.5% (Need 3 more wins from 7 matches)\n2. **India**: 64.2% (Need 4 wins from 6 matches)\n3. **South Africa**: 58.9% (Dark horse with remaining home series)\n\nTest cricket continues to thrive under the contextual urgency of the two-year championship cycle.`,
    featured_image_url: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80',
    author_id: 'user-author-2',
    category_id: 'cat-2',
    status: 'PUBLISHED',
    match_format: 'TEST',
    is_breaking: false,
    is_featured: false,
    read_time_minutes: 7,
    views_count: 5120,
    published_at: new Date('2026-09-22T09:00:00Z').toISOString(),
    created_at: new Date('2026-09-22T07:30:00Z').toISOString(),
    updated_at: new Date('2026-09-22T09:00:00Z').toISOString(),
  },
  {
    id: 'art-5',
    title: 'The Evolution of the Mystery Spinner: From Iftikhar to Varun Chakravarthy and Beyond',
    slug: 'evolution-of-mystery-spin-carrom-ball-analytics',
    excerpt: 'How high-speed cameras, biomechanical tracking, and ball tracking algorithms changed the craft of finger-spin deception forever.',
    content: `Twenty years ago, a carrom ball was treated as an enigmatic sorcery seen once in a generation. Today, digital batting simulators allow batters to view hundreds of deliveries from every conceivable angle before ever stepping onto the field.\n\nYet, the mystery spinner has not become obsolete; they have evolved. By varying arm speeds, revolutions per minute (RPM), and subtly masking their grip behind their torso during approach, modern spinners create hesitation in batter trigger movements.\n\nThis article examines the grip dynamics, wrist releases, and release speeds that keep even the world’s most sophisticated batting lineups second-guessing their footwork.`,
    featured_image_url: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=1200&q=80',
    author_id: 'user-author-2',
    category_id: 'cat-4',
    status: 'PUBLISHED',
    match_format: 'GENERAL',
    is_breaking: false,
    is_featured: false,
    read_time_minutes: 5,
    views_count: 3890,
    published_at: new Date('2026-09-21T16:00:00Z').toISOString(),
    created_at: new Date('2026-09-21T14:00:00Z').toISOString(),
    updated_at: new Date('2026-09-21T16:00:00Z').toISOString(),
  }
];

export const initialComments: Comment[] = [
  {
    id: 'comm-1',
    article_id: 'art-1',
    user_id: 'user-reader',
    content: 'Bumrah in Test cricket is truly a marvel. The spell in South Africa where he bowled those seam-up cutters on a fifth-day pitch remains etched in my mind!',
    status: 'APPROVED',
    created_at: new Date('2026-09-24T11:30:00Z').toISOString(),
    updated_at: new Date('2026-09-24T11:30:00Z').toISOString(),
  },
  {
    id: 'comm-2',
    article_id: 'art-2',
    user_id: 'user-author-1',
    content: 'Brilliant breakdown of the Impact Player consequence. If you are not striking at 180+ in the first four overs now, you are practically giving away the game.',
    status: 'APPROVED',
    created_at: new Date('2026-09-23T16:00:00Z').toISOString(),
    updated_at: new Date('2026-09-23T16:00:00Z').toISOString(),
  }
];
